DB:
    # prod conn string: Driver={ODBC Driver 17 for SQL Server};Server=10.160.20.65\SSQL_2016;Database=dw_motrpac;UID={!db_user_name!};PWD={!db_user_pwd!};
    # New prod conn string: Driver={ODBC Driver 17 for SQL Server};Server=10.9.10.59\SQLVP201606;Database=dw_motrpac;UID={!db_user_name!};PWD={!db_user_pwd!};
    # Local conn string: Driver={ODBC Driver 17 for SQL Server};Server=localhost\sqlexpress;Database=dw_motrpac;UID={!db_user_name!};PWD={!db_user_pwd!}
    # DB connection string
    mdb_conn_str: Driver={ODBC Driver 17 for SQL Server};Server={!server!}};Database={!db_name!}};UID={!db_user_name!};PWD={!db_user_pwd!};
    db_plh_sesrver: "{!server!}"
    db_plh_db_name: "{!db_name!}"
    db_plh_user_name: "{!db_user_name!}"
    db_plh_pwd: "{!db_user_pwd!}"
    env_db_server: ST_DB_SERVER
    env_db_name: ST_DB_NAME
    env_db_user_name: ST_DB_USER_NAME
    env_db_user_pwd: ST_DB_USER_PWD
    # name of the stored proc to be used to load samples to DB
    mdb_sql_proc_load_sample: exec usp_load_single_sample @study_id = {study_id}, @sample_id ='{sample_id}', @json ='{smpl_json}', @dict_json='{dict_json}', @dict_path='{dict_path}', @data_source='{data_source}', @dict_update={dict_update}, @samlpe_update={samlpe_update}

    # name of field templates for updating of stored procedure parameters (specified in "mdb_sql_proc_load_sample")
    fld_tmpl_study_id: '{study_id}'
    fld_tmpl_sample_id: '{sample_id}'
    fld_tmpl_row_json: '{smpl_json}'
    fld_tmpl_dict_json: '{dict_json}'
    fld_tmpl_dict_path: '{dict_path}'
    fld_tmpl_filepath: '{data_source}'
    fld_tmpl_dict_update: '{dict_update}'
    fld_tmpl_samlpe_update: '{samlpe_update}'

Location:
    # path to the folder where all data files are located
    #local path
    #data_folder: D:/MounSinai/MoTrPac_API/ProgrammaticConnectivity/MountSinai_metadata_file_loader/datafiles
    # production path
    # data_folder: J:\Metadata_Processing

    #name of the folder where all logs files will be stored
    log_folder_name: logs
    #processed_folder_name: processed
    #processed_file_copies_max_number: -1 #number of copies of file allowed; -1 - stands for unlimited number of copies, if ommitted the default value from GlobalConst will be used

Logging:
    #main log - log created by the main application
    #file log - log created for each processed file

    #defines log levels to be used for "main" and "file" logs. Usual values are INFO and DEBUG
    main_log_level: INFO  # DEBUG
    #file_log_level: DEBUG

    #name for the each type of log (moved to global_const.py)
    #main_log_name: main_log
    #file_log_name: file_processing_log

Email:
    #default settings for sending emails
    smtp_server: {smtp_server} #smtp.mssm.edu
    env_smtp: ST_SMTP_SERVER
    smtp_server_port: 25
    default_from_email: stas.rirak@mssm.edu
    sent_to_emails: stasrirak.ms@gmail.com,stas.rirak@mssm.edu
    send_emails: True # expected values: True, False

Validate:
    # list of environment variable required to be set for a current user in order to run the application
    environment_variables:
        default: # default list of variables required for all runs
            - ST_DB_SERVER
            - ST_DB_NAME
            - ST_DB_USER_NAME
            - ST_DB_USER_PWD
            - ST_SMTP_SERVER
